### ISSUE TITLE
How to get data-service on our private node ? 

### ISSUE THREAD

**Issue by narmathamuthu** [wavesplatform/data-service#271] opened 2019-10-21 14:04 UTC
Hi team ,

I have completed private node configuration. 

But still now we can't find how to implement api service( like data service - https://api.testnet.wavesplatform.com/v0/ ) . 

So please  explain how to implement that functionality ?

**Comment by dvshur** [comment] 2019-10-21 14:47
Hi, @narmathamuthu. Probably the easiest way is to use our Docker images and some kind of multi-image launch, e.g. docker-compose or Kubernetes, depending on how deep you want to go in your devops efforts.

https://hub.docker.com/r/wavesplatform/blockchain-postgres-sync
https://hub.docker.com/r/wavesplatform/data-service
https://hub.docker.com/r/wavesplatform/data-service-candles
https://hub.docker.com/r/wavesplatform/data-service-pairs

I think this repo Readme.md outlines the general process. If you have more specific questions, please feel free to follow up.

**Comment by narmathamuthu** [comment] 2019-10-21 15:03
@dvshur Okay i will follow up.

I have already done this process ( https://github.com/wavesplatform/blockchain-postgres-sync ). 

Can you explain what we need do next ? 

I have ref.this link - https://github.com/wavesplatform/data-service. 

Can you explain please ?

**Comment by dvshur** [comment] 2019-10-21 15:05
Do you have a working Postgres with some data in it? If you do, you could launch the data service and point it to the database, and it should work. I recommend the Docker image from the link above.

If you want `/pairs` and `/candles` API endpoints to work, you will also need to launch corresponding daemons: `data-service-candles` and `data-service-pairs` images.

**Comment by dvshur** [comment] 2019-10-21 15:08
Also, you could take a look at the repo https://github.com/wavesplatform/deploy-examples
There you can find some examples of deploying the data-service using different technologies (docker-compose, Kubernetes).

**Comment by narmathamuthu** [comment] 2019-10-22 07:04
@dvshur  Okay Fine.

Do you have a working Postgres with some data in it?   ===>> yes ( PFA ). 

![Screenshot from 2019-10-22 12-28-02](https://user-images.githubusercontent.com/55826071/67264074-a70fa380-f4c7-11e9-944a-a139c0f63564.png)

I have some tables migrated using this cmd ( npm run migrate -- --connection postgresql://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$DB ) .

how to run this data-service ?

**Comment by dvshur** [comment] 2019-11-05 13:54
This is mostly a duplicate of #272, I suggest we move the discussion there. Closing this issue.

**Closed by dvshur** 2019-11-05 13:54 UTC
