### ISSUE TITLE
Very old transfers not found in transfers endpoint

### ISSUE THREAD

**Issue by danlutz** [wavesplatform/data-service#200] opened 2019-06-05 06:44 UTC
Hi!

First of, thank you for developing this awesome service! It increases transparency and makes digging into the blockchain very easy.

I'm trying out multiple queries, and noticed a problem:

When I'm querying https://api.wavesplatform.com/v0/transactions/transfer?recipient=XXX

The earliest transactions I can get start at 2017-01-16.
However, I know for sure that for that particular address, there exists some earlier transfers. When I query a particular tx (from 2016) by id, it correctly shows up:

https://api.wavesplatform.com/v0/transactions/all/XXX

Just wanted to let you know :)

Keep up the great work guys!

**Comment by dvshur** [comment] 2019-06-05 10:38
Hi, @danlutz! Thank you for using our service and providing feedback.

Could you provide a more specific example? Like a transaction ID for which the bug reproduces?

**Comment by danlutz** [comment] 2019-06-06 15:32
For privacy reasons I do not want to provide a txid in public, i can say one of them was in Block 70, but basically it shows no txs that happende in 2016 for me :)

I could send you a txid in private if you want!

**Comment by dvshur** [comment] 2019-07-03 14:25
Sorry for taking long to response.

The reason why you haven't been able to find old transfers is because they were not called 'transfers' at the time. Those old transactions have been called `Payment`, `type: 2` transactions that currently are deprecated. In order to find those you should use a `/payment` endpoint instead of the `/transfer` one. Example:

https://api.wavesplatform.com/v0/transactions/payment
https://api.wavesplatform.com/v0/transactions/payment/Yoxujmdq22KaXqopLCYZfvjqf14HRKD1c9DhsqWR9CrpFE1vfoYcpaPeLwNDtUAWpGccf6Sw8otUmhptP2rEJgP

**Comment by dvshur** [comment] 2019-07-08 12:31
I hope it helped. If you have any more questions, feel free to ask. Closing the issue.

**Closed by dvshur** 2019-07-08 12:31 UTC
